export const REWARD_ACCRUAL_70_OUTPUT_SCHEMA = {
  startRow: 15,
  sheetName: "Відомість загальна",
  fields: [
    { name: "index", column: "A", styleId: "default", merge: { rows: 2, columns: "A" } },
    { name: "unit", column: "B", styleId: "default", merge: { rows: 2, columns: "B" } },
    { name: "position", column: "C", styleId: "default", merge: { rows: 2, columns: "C" } },
    { name: "militaryRank", column: "D", styleId: "default", merge: { rows: 2, columns: "D" } },
    { name: "fullName", column: "E", styleId: "default", merge: { rows: 2, columns: "E" } },
    { name: "taxPayerId", column: "F", styleId: "default", merge: { rows: 2, columns: "F" } },
    { name: "initialAmountOfDays", column: "H", styleId: "default" },
    { name: "januaryDays", column: "I", styleId: "default" },
    { name: "januaryReason", column: "I", styleId: "default", rowShift: 1 },
    { name: "februaryDays", column: "J", styleId: "default" },
    { name: "februaryReason", column: "J", styleId: "default", rowShift: 1 },
    { name: "marchDays", column: "K", styleId: "default" },
    { name: "marchReason", column: "K", styleId: "default", rowShift: 1 },
    { name: "aprilDays", column: "L", styleId: "default" },
    { name: "aprilReason", column: "L", styleId: "default", rowShift: 1 },
    { name: "mayDays", column: "M", styleId: "default" },
    { name: "mayReason", column: "M", styleId: "default", rowShift: 1 },
    { name: "juneDays", column: "N", styleId: "default" },
    { name: "juneReason", column: "N", styleId: "default", rowShift: 1 },
    { name: "julyDays", column: "O", styleId: "default" },
    { name: "julyReason", column: "O", styleId: "default", rowShift: 1 },
    { name: "augustDays", column: "P", styleId: "default" },
    { name: "augustReason", column: "P", styleId: "default", rowShift: 1 },
    { name: "septemberDays", column: "Q", styleId: "default" },
    { name: "septemberReason", column: "Q", styleId: "default", rowShift: 1 },
    { name: "octoberDays", column: "R", styleId: "default" },
    { name: "octoberReason", column: "R", styleId: "default", rowShift: 1 },
    { name: "novemberDays", column: "S", styleId: "default" },
    { name: "novemberReason", column: "S", styleId: "default", rowShift: 1 },
    { name: "decemberDays", column: "T", styleId: "default" },
    { name: "decemberReason", column: "T", styleId: "default", rowShift: 1 },
    { name: "totalEligibleDays", column: "U", styleId: "default" },
    { name: "numberOfPaymentOrdersInTheYear", column: "V", styleId: "default" },
    { name: "numberOfPaymentOrders", column: "W", styleId: "default" },
    { name: "paymentOrders", column: "W", styleId: "default", rowShift: 1 },
    { name: "remainingDays", column: "X", styleId: "default" },
  ],
  // predefined: {
  //   data: [
  //     { cell: "A1", value: "№ з/п", styleId: "header" },
  //     { cell: "B1", value: "Підрозділ", styleId: "header" },
  //     { cell: "C1", value: "Посада", styleId: "header" },
  //     { cell: "D1", value: "Звання", styleId: "header" },
  //     { cell: "E1", value: "ПІБ", styleId: "header" },
  //     { cell: "F1", value: "ІПН", styleId: "header" },
  //     {
  //       cell: "H1",
  //       value: "Перенесена залишкова кількість днів, за які не виплачено однарозову винагороду",
  //       styleId: "header",
  //     },
  //     { cell: "I1", value: "січень", styleId: "header" },
  //     { cell: "J1", value: "лютий", styleId: "header" },
  //     { cell: "K1", value: "березень", styleId: "header" },
  //     { cell: "L1", value: "квітень", styleId: "header" },
  //     { cell: "M1", value: "травень", styleId: "header" },
  //     { cell: "N1", value: "червень", styleId: "header" },
  //     { cell: "O1", value: "липень", styleId: "header" },
  //     { cell: "P1", value: "серпень", styleId: "header" },
  //     { cell: "Q1", value: "вересень", styleId: "header" },
  //     { cell: "R1", value: "жовтень", styleId: "header" },
  //     { cell: "S1", value: "листопад", styleId: "header" },
  //     { cell: "T1", value: "грудень", styleId: "header" },
  //     {
  //       cell: "U1",
  //       value: "Сумарна кількість днів виконання бойових (спеціальних) завдань",
  //       styleId: "header",
  //     },
  //     {
  //       cell: "V1",
  //       value:
  //         "Кількість сумарно обчислених періодів по 30 днів, за які виплачено одноразову винагороду",
  //       styleId: "header",
  //     },
  //     {
  //       cell: "W1",
  //       value: "Номери та дати  наказів про виплату одноразової винагороди",
  //       styleId: "header",
  //     },
  //     {
  //       cell: "X1",
  //       value: "Залишкова кількість днів, за які не виплачено одноразову винагороду",
  //       styleId: "header",
  //     },
  //   ],
  //   columnStyles: [
  //     { column: "F", id: "autofit" },
  //     { column: "E", id: "wide" },
  //     { column: "W", id: "wide" },
  //   ],
  // },
};
